-- Supabase Project: trdoainmejxanrownbuz
-- Click: https://supabase.com/dashboard/project/trdoainmejxanrownbuz/sql/new

-- Add blueprint_112 column to brand_cartridges
-- This stores the full Jon Benson 112-point marketing blueprint

ALTER TABLE brand_cartridges
ADD COLUMN IF NOT EXISTS blueprint_112 JSONB DEFAULT NULL;

-- Add index for faster lookups
CREATE INDEX IF NOT EXISTS idx_brand_cartridges_blueprint_112
ON brand_cartridges USING gin (blueprint_112);

-- Comment explaining the structure
COMMENT ON COLUMN brand_cartridges.blueprint_112 IS
'Jon Benson 112-point marketing blueprint. Generated by BlueprintChip from basic brand data. Includes: bio, avatars, pain points, desires, objections, offers, testimonials, lessons, etc.';
